### ISSUE TITLE
file save to wrong path

### ISSUE THREAD

**Issue by tmjpugh** [snowzach/hassdoods#2]
I want save file in folder like /camera/date/time.jpg
/Camera folder will already exist but /date is not created and must be created by doods. What is strange is error show in HA log about missing folder but also file is saved as /camera/time.jpg when I would expect it not save at all.

**Comment by snowzach** [comment]
What does your config look like?

**Comment by tmjpugh** [comment]
```
###SOUTHGATE2###
- platform: doods
  scan_interval: 1
  url: "http://162.160.27.12:6020"
  detector: default
  file_out:
    - "/config/dcim/doods/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/motioneye/{{ camera_entity.split('.')[1] }}/{{ now().strftime('%Y%m%d') }}/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d-%H%M%S') }}.jpg"
  source:
    - entity_id: camera.south_gate2
  confidence: 40
  labels:
    - name: car
      confidence: 45
      area:
        top: 0.2
    - dog
    - name: person
      confidence: 65
    - name: truck
      confidence: 50
      area:
        top: 0.2

```
