### ISSUE TITLE
Bad Data

### ISSUE THREAD

**Issue by wesdottoday** [snowzach/hassdoods#5]
Hi, I'm using DOODS (or attempting to) and I'm running into an error in Home Assistant. I have Hikvision cameras.

> Unable to process image, bad data

I'm able to pass a base64 encoded image manually to the DOODS container. 

My camera still image path is: `http://user:password@10.45.3.21/ISAPI/Streaming/channels/1/picture` and I can pull a good image using it manually (and in Lovelace).

My config looks like this:

```
# automation.yaml
  - alias: Front Door Line Crossing
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_line_crossing
    action:
      - service: image_processing.scan
        entity_id: image_processing.doods_front_door

# image_processing.yaml
image_processing:
  - platform: doods
    scan_interval: 1000
    url: !secret doods_url
    timeout: 60
    detector: default
    source:
      - entity_id: camera.backyard
      - entity_id: camera.backyard_west_gate
      - entity_id: camera.driveway
      - entity_id: camera.front_door
      - entity_id: camera.garage
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 50
    labels:
      - name: person
        confidence: 50
      - name: car
        confidence: 50
      - name: truck
```

I would love some debugging assistance!
